# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-07 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_post', models.IntegerField()),
                ('title', models.CharField(default='', max_length=25)),
                ('content', models.TextField()),
                ('tags', models.TextField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('author_id', models.IntegerField()),
            ],
            options={
                'db_table': 'shmoterapp_post',
            },
        ),
    ]
